/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.EquipamentoJpaController;
import com.mycompany.academia.entidades.Equipamento;
import com.mycompany.academia.lista.EquipamentoModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class EquipamentoEdita extends javax.swing.JPanel {

    private final EquipamentoJpaController controller;
    private final Equipamento equipamento;
    private final JDialog dialog;
    private final EquipamentoModel equipamento_model;

    /**
     * Creates new form ExercicioEdita
     *
     * @param equip
     * @param jDialog
     * @param model
     */
    public EquipamentoEdita(Equipamento equip, JDialog jDialog, EquipamentoModel model) {
        controller = new EquipamentoJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
        equipamento = equip;
        dialog = jDialog;
        equipamento_model = model;
        initComponents();

        salvar.addActionListener((e) -> {
            if ("".equals(nome_equipamento.getText())) {
                JOptionPane.showMessageDialog(this, "Preencha o nome do exercicio");
                return;
            }

            this.equipamento.setNomeEquipamento(nome_equipamento.getText());
            if (this.equipamento.getIdEquipamento() == null) {
                controller.create(this.equipamento);
                equipamento_model.adicionarNovo(this.equipamento);
            } else {
                try {
                    controller.edit(this.equipamento);
                    equipamento_model.atualizar(this.equipamento);
                } catch (Exception ex1) {
                    Logger.getLogger(EquipamentoEdita.class.getName()).log(Level.SEVERE, null, ex1);
                }
            }
            dialog.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_equipamento = new javax.swing.JTextField();
        nome_equipamento = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(280, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(280, 150));

        jLabel1.setText("ID");

        jLabel2.setText("Nome do Exercicio");

        id_equipamento.setEditable(false);
        id_equipamento.setColumns(8);
        if (equipamento.getIdEquipamento()!= null) {
            id_equipamento.setText(equipamento.getIdEquipamento().toString());
        }

        nome_equipamento.setColumns(8);
        if (equipamento.getNomeEquipamento() != null) {
            nome_equipamento.setText(equipamento.getNomeEquipamento());
        }

        salvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nome_equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id_equipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nome_equipamento;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
