/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.ImagemJpaController;
import com.mycompany.academia.controle.ImagemKeywordJpaController;
import com.mycompany.academia.controle.KeywordsJpaController;
import com.mycompany.academia.controle.exceptions.NonexistentEntityException;
import com.mycompany.academia.entidades.Imagem;
import com.mycompany.academia.entidades.ImagemKeyword;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JDialog;
import com.mycompany.academia.entidades.Keywords;
import com.mycompany.academia.renderer.RendererImagem;
import com.mycompany.academia.renderer.RendererKeyword;
import javax.swing.ListCellRenderer;

/**
 *
 * @author paulo
 */
public class ImagemKeywordEdita extends javax.swing.JPanel {

    // conexão com o banco de dados 
    private final ImagemKeywordJpaController imagemKeywordJpaController = new ImagemKeywordJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
    private final ImagemJpaController imagemJpaController = new ImagemJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
    private final KeywordsJpaController keywordsJpaController = new KeywordsJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));

    // dados para o combobox
    private final Imagem[] listaImagens = imagemJpaController.findImagemEntities().toArray(Imagem[]::new);
    private final Keywords[] listaKeywords = keywordsJpaController.findKeywordsEntities().toArray(Keywords[]::new);
    // renderer para o combobox
    private final ListCellRenderer<? super Imagem> rendererImagem = new RendererImagem();
    private final ListCellRenderer<? super Keywords> rendererKeyword = new RendererKeyword();

    // objeto sendo criado ou editado
    // janela para ser fechada quando a transação com o banco de dados for concluida
    private final ImagemKeyword imagem_keyword;
    private final JDialog owner;

    /**
     * Creates new form edita
     *
     * @param img_kw
     * @param parent
     */
    public ImagemKeywordEdita(ImagemKeyword img_kw, JDialog parent) {
        imagem_keyword = img_kw;
        owner = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        labelKeyword = new javax.swing.JLabel();
        entradaId = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        entradaImagem = new javax.swing.JComboBox<>();
        entradaKeyword = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(280, 212));

        labelId.setText("Id");

        labelImagem.setText("Imagem");

        labelKeyword.setText("Keyword");

        entradaId.setEditable(false);
        entradaId.setColumns(8);
        entradaId.setToolTipText("Id da imagem");
        entradaId.setFocusable(false);
        if (imagem_keyword.getId() != null) {
            entradaId.setText(imagem_keyword.getId().toString());
        }

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        entradaImagem.setModel(new javax.swing.DefaultComboBoxModel<>(listaImagens));
        entradaImagem.setRenderer(rendererImagem);

        entradaKeyword.setModel(new javax.swing.DefaultComboBoxModel<>(listaKeywords));
        entradaKeyword.setRenderer(rendererKeyword);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId)
                            .addComponent(labelImagem)
                            .addComponent(labelKeyword))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(entradaId)
                            .addComponent(entradaImagem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(botaoSalvar)
                    .addComponent(entradaKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKeyword)
                    .addComponent(entradaKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImagem)
                    .addComponent(entradaImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // se o objeto sendo editado nao tiver id, id for null, cria um objeto novo no banco de dados
        // se o objeto sendo editado ja tiver um id atuliza o objeto e salvo no banco de dados.
        if (imagem_keyword.getId() == null) {
            // associa uma imagem a uma keyword da entidade imagem_keyword para ser salvo no banco de dados. Id é definido automaticamente.
            imagem_keyword.setImagem((Imagem) entradaImagem.getSelectedItem());
            imagem_keyword.setKeyword((Keywords) entradaKeyword.getSelectedItem());

            try {
                // começa a transação para criar uma nova entidade no banco.
                imagemKeywordJpaController.create(imagem_keyword);
            } catch (Exception ex) {
                Logger.getLogger(ImagemKeywordEdita.class.getName()).log(Level.SEVERE, null, ex);
            }
            owner.dispose();
        } else {
            imagem_keyword.setImagem((Imagem) entradaImagem.getSelectedItem());
            imagem_keyword.setKeyword((Keywords) entradaKeyword.getSelectedItem());
            try {
                // começa a transação para editar a entidade no banco.
                imagemKeywordJpaController.edit(imagem_keyword);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(ImagemKeywordEdita.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ImagemKeywordEdita.class.getName()).log(Level.SEVERE, null, ex);
            }
            owner.dispose();
        }

    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField entradaId;
    private javax.swing.JComboBox<Imagem> entradaImagem;
    private javax.swing.JComboBox<Keywords> entradaKeyword;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelImagem;
    private javax.swing.JLabel labelKeyword;
    // End of variables declaration//GEN-END:variables
}
