/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.ImagemJpaController;
import com.mycompany.academia.controle.exceptions.NonexistentEntityException;
import com.mycompany.academia.entidades.Imagem;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.persistence.Persistence;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author paulo
 */
public class ImagemEdita extends javax.swing.JPanel {

    private Imagem imagem;
    private File file;
    private JDialog owner;

    /**
     * Creates new form edita
     *
     * @param img
     * @param parent
     */
    public ImagemEdita(Imagem img, JDialog parent) {
        imagem = img;
        owner = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        entradaId = new javax.swing.JTextField();
        entradaDescricao = new javax.swing.JTextField();
        caminhoImagem = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        entradaImagem = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(280, 212));

        labelId.setText("Id");

        labelImagem.setText("Imagem");

        labelDescricao.setText("Descricao");

        entradaId.setEditable(false);
        entradaId.setColumns(8);
        entradaId.setToolTipText("Id da imagem");
        entradaId.setFocusable(false);
        if (imagem.getId() != null) {
            entradaId.setText(imagem.getId().toString());
        }

        entradaDescricao.setColumns(8);
        entradaDescricao.setToolTipText("Uma breve descricao da imagem");
        entradaDescricao.setText(imagem.getDescricao());

        caminhoImagem.setEditable(false);
        caminhoImagem.setColumns(8);
        caminhoImagem.setToolTipText("Nome do arquivo selecionado");
        caminhoImagem.setFocusable(false);
        if (imagem.getImagem() != null) {
            caminhoImagem.setText(imagem.getImagem().toString());
        }

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        entradaImagem.setText("...");
        entradaImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId)
                            .addComponent(labelImagem)
                            .addComponent(labelDescricao))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caminhoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entradaImagem)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescricao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caminhoImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelImagem)
                    .addComponent(entradaImagem))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void entradaImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaImagemActionPerformed
        // cria um dialog para escolher um arquivo
        JFileChooser fc = new JFileChooser();
        // filtra somente arquivos .png
        fc.setAcceptAllFileFilterUsed(false);
        fc.addChoosableFileFilter(new FileNameExtensionFilter("png files", "png"));
        // salva o arquivo selecionado na variavel file, tambem muda o texto de caminhoImagem para o nome do arquivo selecionado
        if (evt.getSource() == entradaImagem) {
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                file = fc.getSelectedFile();
                caminhoImagem.setText(file.getName());
            }
        }
    }//GEN-LAST:event_entradaImagemActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (imagem.getId() == null) {
            // entidade controle com as funções do CRUD.
            ImagemJpaController ijc = new ImagemJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));

            // Cria um ByteArray com a imagem selecionada pelo usuario.
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try {
                ImageIO.write(ImageIO.read(file), "png", baos);
            } catch (IOException ex) {
                Logger.getLogger(ImagemEdita.class.getName()).log(Level.SEVERE, null, ex);
            }

            // define a imagem e descrição da entidade imagem para ser salvo no banco de dados. Id é definido automaticamente.
            imagem.setImagem(baos.toByteArray());
            imagem.setDescricao(entradaDescricao.getText());

            // começa a transação para criar uma nova entidade no banco.
            ijc.create(imagem);
            owner.dispose();
        } else {
            ImagemJpaController ijc = new ImagemJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
            // Se editando e nenhum arquivo selecionado
            // a nova imagem continua sendo a imagem antiga
            if (file == null) {
                imagem.setImagem(imagem.getImagem());
            } else { // se algum arquivo for selecionado então transforma em byte array e salva como a nova imagem
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                try {
                    ImageIO.write(ImageIO.read(file), "png", baos);
                } catch (IOException ex) {
                    Logger.getLogger(ImagemEdita.class.getName()).log(Level.SEVERE, null, ex);
                }
                imagem.setImagem(baos.toByteArray());
            }
            imagem.setDescricao(entradaDescricao.getText());

            try {
                // começa a transação para criar uma nova entidade no banco.
                ijc.edit(imagem);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(ImagemEdita.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(ImagemEdita.class.getName()).log(Level.SEVERE, null, ex);
            }
            owner.dispose();
        }

    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField caminhoImagem;
    private javax.swing.JTextField entradaDescricao;
    private javax.swing.JTextField entradaId;
    private javax.swing.JButton entradaImagem;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelImagem;
    // End of variables declaration//GEN-END:variables
}
