/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.KeywordsJpaController;
import com.mycompany.academia.controle.exceptions.NonexistentEntityException;
import com.mycompany.academia.entidades.Keywords;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JDialog;

/**
 *
 * @author paulo
 */
public class KeywordsEdita extends javax.swing.JPanel {
    // conexão com o banco de dados 

    private final KeywordsJpaController keywordsJpaController = new KeywordsJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));

    // objeto sendo criado ou editado
    // janela para ser fechada quando a transação com o banco de dados for concluida
    private final Keywords keyword;
    private final JDialog owner;

    /**
     * Creates new form edita
     *
     * @param kw
     * @param parent
     */
    public KeywordsEdita(Keywords kw, JDialog parent) {
        keyword = kw;
        owner = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelKeyword = new javax.swing.JLabel();
        entradaId = new javax.swing.JTextField();
        entradaKeyword = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(280, 212));

        labelId.setText("Id");

        labelKeyword.setText("Keyword");

        entradaId.setEditable(false);
        entradaId.setColumns(8);
        entradaId.setToolTipText("Id da imagem");
        entradaId.setFocusable(false);
        if (keyword.getId() != null) {
            entradaId.setText(keyword.getId().toString());
        }

        entradaKeyword.setColumns(8);
        entradaKeyword.setToolTipText("Uma breve descricao da imagem");
        entradaKeyword.setText(keyword.getKeyword());

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId)
                            .addComponent(labelKeyword))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entradaKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botaoSalvar))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKeyword))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // se o objeto sendo editado nao tiver id, id for null, cria um objeto novo no banco de dados
        // se o objeto sendo editado ja tiver um id atuliza o objeto e salvo no banco de dados.
        if (keyword.getId() == null) {
            // keyword.keyword = user input
            keyword.setKeyword(entradaKeyword.getText());

            // adiciona a nova entrada no banco de dados
            keywordsJpaController.create(keyword);
            owner.dispose();
        } else {
            keyword.setKeyword(entradaKeyword.getText());

            // atualiza a entrada no banco de dados
            try {
                keywordsJpaController.edit(keyword);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(KeywordsEdita.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(KeywordsEdita.class.getName()).log(Level.SEVERE, null, ex);
            }
            // fecha o dialog
            owner.dispose();
        }

    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField entradaId;
    private javax.swing.JTextField entradaKeyword;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelKeyword;
    // End of variables declaration//GEN-END:variables
}
