/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.ImagemJpaController;
import com.mycompany.academia.controle.MovimentoJpaController;
import com.mycompany.academia.controle.exceptions.NonexistentEntityException;
import com.mycompany.academia.entidades.Imagem;
import com.mycompany.academia.entidades.Movimento;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JDialog;

/**
 *
 * @author paulo
 */
public class MovimentoEdita extends javax.swing.JPanel {

    // conexão com o banco de dados 
    private ImagemJpaController imagemJpaController = new ImagemJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
    private MovimentoJpaController movimentoJpaController = new MovimentoJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));

    // dados para o combobox
    private Imagem[] listaImagens = imagemJpaController.findImagemEntities().toArray(Imagem[]::new);

    // objeto sendo criado ou editado
    // janela para ser fechada quando a transação com o banco de dados for concluida
    private Movimento movimento;
    private JDialog owner;

    /**
     * Creates new form edita
     *
     * @param mov
     * @param parent
     */
    public MovimentoEdita(Movimento mov, JDialog parent) {
        movimento = mov;
        owner = parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelImagem = new javax.swing.JLabel();
        labelDescricao = new javax.swing.JLabel();
        entradaId = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        entradaImagemAntes = new javax.swing.JComboBox<>();
        entradaImagemDepois = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(280, 212));

        labelId.setText("Id");

        labelImagem.setText("Imagem Depois");

        labelDescricao.setText("Imagem Antes");

        entradaId.setEditable(false);
        entradaId.setColumns(8);
        entradaId.setToolTipText("Id da imagem");
        entradaId.setFocusable(false);
        if (movimento.getId() != null) {
            entradaId.setText(movimento.getId().toString());
        }

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        entradaImagemAntes.setModel(new javax.swing.DefaultComboBoxModel<>(listaImagens));

        entradaImagemDepois.setModel(new javax.swing.DefaultComboBoxModel<>(listaImagens));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelId)
                            .addComponent(labelImagem)
                            .addComponent(labelDescricao))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(entradaId)
                            .addComponent(entradaImagemDepois, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entradaImagemAntes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(botaoSalvar))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(entradaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entradaImagemAntes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescricao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelImagem)
                    .addComponent(entradaImagemDepois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botaoSalvar)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // se o objeto sendo editado nao tiver id, id for null, cria um objeto novo no banco de dados
        // se o objeto sendo editado ja tiver um id atuliza o objeto e salvo no banco de dados.
        if (movimento.getId() == null) {
            // define as imagens de antes e depois do objeto
            movimento.setAntes((Imagem) entradaImagemAntes.getSelectedItem());
            movimento.setDepois((Imagem) entradaImagemAntes.getSelectedItem());

            // cria o novo objeto no banco de dados e fecha JDialog
            movimentoJpaController.create(movimento);
            owner.dispose();
        } else {
            // define as imagens de antes e depois do objeto
            movimento.setAntes((Imagem) entradaImagemAntes.getSelectedItem());
            movimento.setDepois((Imagem) entradaImagemAntes.getSelectedItem());

            // atualiza o objeto no banco de dados
            try {
                movimentoJpaController.edit(movimento);
            } catch (NonexistentEntityException ex) {
                Logger.getLogger(MovimentoEdita.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(MovimentoEdita.class.getName()).log(Level.SEVERE, null, ex);
            }
            // fecha o JDialog
            owner.dispose();
        }

    }//GEN-LAST:event_botaoSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField entradaId;
    private javax.swing.JComboBox<Imagem> entradaImagemAntes;
    private javax.swing.JComboBox<Imagem> entradaImagemDepois;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelImagem;
    // End of variables declaration//GEN-END:variables
}
