/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.edita;

import com.mycompany.academia.controle.MusculoAlvoJpaController;
import com.mycompany.academia.entidades.MusculoAlvo;
import com.mycompany.academia.lista.MusculoAlvoModel;
import javax.persistence.Persistence;
import javax.swing.JDialog;

/**
 *
 * @author paulo
 */
public class MusculoAlvoEdita extends javax.swing.JPanel {

    private final MusculoAlvoJpaController controller;
    private final MusculoAlvo musculoAlvo;
    private final JDialog dialog;
    private final MusculoAlvoModel musculoAlvoModel;

    /**
     * Creates new form MusculoAlvoEdita
     *
     * @param ma
     * @param dg
     * @param model
     */
    public MusculoAlvoEdita(MusculoAlvo ma, JDialog dg, MusculoAlvoModel model) {
        controller = new MusculoAlvoJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
        musculoAlvo = ma;
        dialog = dg;
        musculoAlvoModel = model;
        initComponents();

        salvar.addActionListener((e) -> {
            dialog.dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        musculo_alvo_id = new javax.swing.JTextField();
        alvo_entrada = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(280, 244));

        jLabel1.setText("ID");

        jLabel2.setText("Alvo");

        musculo_alvo_id.setEditable(false);
        musculo_alvo_id.setColumns(8);
        if (musculoAlvo.getId() != null) {
            musculo_alvo_id.setText(musculoAlvo.getId().toString());
        }

        alvo_entrada.setColumns(8);
        if (musculoAlvo.getAlvo() != null) {
            alvo_entrada.setText(musculoAlvo.getAlvo());
        }

        salvar.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musculo_alvo_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alvo_entrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(musculo_alvo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alvo_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(salvar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alvo_entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField musculo_alvo_id;
    private javax.swing.JButton salvar;
    // End of variables declaration//GEN-END:variables
}
