/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.rotina.paginas;

import com.mycompany.academia.rotina.RotinaMenuLateral;

/**
 *
 * @author paulo
 */
public class HomePage extends javax.swing.JPanel {

    private final RotinaMenuLateral parent;

    /**
     * Creates new form HomePage
     *
     * @param parent_window
     */
    public HomePage(RotinaMenuLateral parent_window) {
        parent = parent_window;

        initComponents();
        bicepsBotao.addActionListener((e) -> {
            parent.showBiceps();
        });
        tricepsBotao.addActionListener((e) -> {
            parent.showTriceps();
        });
        antebracoBotao.addActionListener((e) -> {
            parent.showAntebraco();
        });
        ombroBotao.addActionListener((e) -> {
            parent.showOmbro();
        });
        peitoBotao.addActionListener((e) -> {
            parent.showPeito();
        });
        abdomenBotao.addActionListener((e) -> {
            parent.showAbdomen();
        });
        costaBotao.addActionListener((e) -> {
            parent.showCosta();
        });
        pernaBotao.addActionListener((e) -> {
            parent.showPerna();
        });
        cardioBotao.addActionListener((e) -> {
            parent.showCardio();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        bicepsBotao = new javax.swing.JButton();
        tricepsBotao = new javax.swing.JButton();
        antebracoBotao = new javax.swing.JButton();
        ombroBotao = new javax.swing.JButton();
        peitoBotao = new javax.swing.JButton();
        abdomenBotao = new javax.swing.JButton();
        costaBotao = new javax.swing.JButton();
        pernaBotao = new javax.swing.JButton();
        cardioBotao = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(370, 551));

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        bicepsBotao.setText("biceps");
        jPanel1.add(bicepsBotao);

        tricepsBotao.setText("triceps");
        jPanel1.add(tricepsBotao);

        antebracoBotao.setText("antebraco");
        jPanel1.add(antebracoBotao);

        ombroBotao.setText("ombro");
        jPanel1.add(ombroBotao);

        peitoBotao.setText("peito");
        jPanel1.add(peitoBotao);

        abdomenBotao.setText("abdomen");
        jPanel1.add(abdomenBotao);

        costaBotao.setText("costa");
        jPanel1.add(costaBotao);

        pernaBotao.setText("perna");
        jPanel1.add(pernaBotao);

        cardioBotao.setText("cardio");
        jPanel1.add(cardioBotao);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abdomenBotao;
    private javax.swing.JButton antebracoBotao;
    private javax.swing.JButton bicepsBotao;
    private javax.swing.JButton cardioBotao;
    private javax.swing.JButton costaBotao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ombroBotao;
    private javax.swing.JButton peitoBotao;
    private javax.swing.JButton pernaBotao;
    private javax.swing.JButton tricepsBotao;
    // End of variables declaration//GEN-END:variables
}
