/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.view.rotina.paginas;

import com.mycompany.academia.controle.MusculoAlvoControle;
import com.mycompany.academia.model.entidades.MusculoAlvo;
import com.mycompany.academia.view.rotina.RotinaMenuLateral;
import java.util.List;
import javax.swing.JButton;

/**
 *
 * @author paulo
 */
public class HomePage extends javax.swing.JPanel {

    private final MusculoAlvoControle musculoAlvoControle = new MusculoAlvoControle();
    private List<MusculoAlvo> listaMusculoAlvo = musculoAlvoControle.getListaMusculoAlvo();

    /**
     * Creates new form HomePage
     *
     * @param parent_window
     */
    public HomePage(RotinaMenuLateral parent_window) {
        initComponents();
        adicionarBotoes(parent_window);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(370, 551));

        jPanel1.setLayout(new java.awt.GridLayout(0, 3));
        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void atualizar(RotinaMenuLateral parent_window) {
        listaMusculoAlvo = musculoAlvoControle.getListaMusculoAlvo();
        adicionarBotoes(parent_window);
    }

    private void adicionarBotoes(RotinaMenuLateral parent_window) {
        jPanel1.removeAll();
        listaMusculoAlvo.forEach((musculo_alvo) -> {
            JButton botao = new JButton(musculo_alvo.getNomeAlvo());
            botao.addActionListener((e) -> {
                parent_window.showListarExercicios(musculo_alvo.getExercicioList());
            });
            jPanel1.add(botao);
        });
    }

}
