/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.academia.lista;

import com.mycompany.academia.controle.EquipamentoJpaController;
import com.mycompany.academia.controle.exceptions.IllegalOrphanException;
import com.mycompany.academia.controle.exceptions.NonexistentEntityException;
import com.mycompany.academia.edita.EquipamentoEdita;
import com.mycompany.academia.entidades.Equipamento;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.Persistence;
import javax.swing.JDialog;

/**
 *
 * @author paulo
 */
public class EquipamentoLista extends javax.swing.JInternalFrame {

    private final EquipamentoJpaController controller;
    private final EquipamentoModel model;

    /**
     * Creates new form EquipamentoLista
     */
    public EquipamentoLista() {
        controller = new EquipamentoJpaController(Persistence.createEntityManagerFactory("com.mycompany_academia_jar_1PU"));
        model = new EquipamentoModel(controller.findEquipamentoEntities());
        initComponents();

        deletar_equipamento.addActionListener((e) -> {
            int linha_selecionada = tabela_lista_equipamentos.getSelectedRow();
            Integer id_entidade = Integer.valueOf(tabela_lista_equipamentos.getValueAt(linha_selecionada, 0).toString());

            try {
                controller.destroy(id_entidade);
                model.deletar(linha_selecionada);
            } catch (NonexistentEntityException | IllegalOrphanException ex) {
                Logger.getLogger(EquipamentoLista.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        adicionar_novo_equipamento.addActionListener((e) -> {
            JDialog dialog = new JDialog();
            EquipamentoEdita formulario_edita = new EquipamentoEdita(new Equipamento(), dialog, model);
            dialog.add(formulario_edita);
            dialog.setSize(new Dimension(300, 200));

            dialog.setVisible(true);
        });

        editar_equipamento.addActionListener((e) -> {
            JDialog dialog = new JDialog();
            int linha_selecionada = tabela_lista_equipamentos.getSelectedRow();
            Integer id_entidade = Integer.valueOf(tabela_lista_equipamentos.getValueAt(linha_selecionada, 0).toString());
            Equipamento equipamento = controller.findEquipamento(id_entidade);
            EquipamentoEdita formulario_edita = new EquipamentoEdita(equipamento, dialog, model);
            dialog.add(formulario_edita);
            dialog.setSize(new Dimension(300, 200));

            dialog.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionar_novo_equipamento = new javax.swing.JButton();
        deletar_equipamento = new javax.swing.JButton();
        editar_equipamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_lista_equipamentos = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(800, 480));

        adicionar_novo_equipamento.setText("Criar");

        deletar_equipamento.setText("Deletar");

        editar_equipamento.setText("Editar");

        tabela_lista_equipamentos.setModel(model);
        jScrollPane1.setViewportView(tabela_lista_equipamentos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionar_novo_equipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletar_equipamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editar_equipamento, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(adicionar_novo_equipamento)
                .addGap(18, 18, 18)
                .addComponent(deletar_equipamento)
                .addGap(18, 18, 18)
                .addComponent(editar_equipamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_novo_equipamento;
    private javax.swing.JButton deletar_equipamento;
    private javax.swing.JButton editar_equipamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_lista_equipamentos;
    // End of variables declaration//GEN-END:variables

    public EquipamentoModel getModel() {
        return model;
    }

}
