/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.rotina;

import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author paulo
 */
public class RotinaDireita extends javax.swing.JPanel {

    public DefaultListModel<String> data = new DefaultListModel<>();

    /**
     * Creates new form RotinaDireita
     */
    public RotinaDireita() {
        initComponents();
        // remove um exercicio da lista
//        deletarBotao.addActionListener((e) -> {
//            if (!listaA.isSelectionEmpty()) {
//                data.remove(listaA.getSelectedIndex());
//            }
//        });
        adicionar_nova_lista.addActionListener((e) -> {
            JList<String> nova_janela = new JList<>();
            nova_janela.setModel(data);

            painel_lista.addTab("lista " + (painel_lista.getTabCount() + 1), nova_janela);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_lista = new javax.swing.JTabbedPane();
        adicionar_nova_lista = new javax.swing.JButton();
        deletar_selecao = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(819, 551));

        adicionar_nova_lista.setText("Nova Lista");

        deletar_selecao.setText("Remover Selecionado");

        imprimir.setText("Imprimir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painel_lista, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletar_selecao)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(adicionar_nova_lista)
                                .addGap(30, 30, 30)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(imprimir)
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_lista, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(adicionar_nova_lista)
                .addGap(18, 18, 18)
                .addComponent(deletar_selecao)
                .addGap(18, 18, 18)
                .addComponent(imprimir)
                .addContainerGap(387, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_nova_lista;
    private javax.swing.JButton deletar_selecao;
    private javax.swing.JButton imprimir;
    private javax.swing.JTabbedPane painel_lista;
    // End of variables declaration//GEN-END:variables
}
