/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.academia.view.exercicio;

import com.mycompany.academia.controle.ExercicioControle;
import com.mycompany.academia.model.entidades.Exercicio;
import java.awt.Dimension;
import javax.swing.JDialog;

/**
 *
 * @author paulo
 */
public class ExercicioLista extends javax.swing.JFrame {

    private final ExercicioControle exercicioControle;
    private final ExercicioModel exercicioModel;

    /**
     * Creates new form ExercicioLista
     */
    public ExercicioLista() {
        exercicioControle = new ExercicioControle();
        exercicioModel = exercicioControle.getExercicioModel();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionar_novo_exercicio = new javax.swing.JButton();
        deletar_exercicio = new javax.swing.JButton();
        editar_exercicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_lista_exercicios = new javax.swing.JTable();

        setTitle("Lista De Exercicios");

        adicionar_novo_exercicio.setText("Criar");
        adicionar_novo_exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionar_novo_exercicioActionPerformed(evt);
            }
        });

        deletar_exercicio.setText("Deletar");
        deletar_exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_exercicioActionPerformed(evt);
            }
        });

        editar_exercicio.setText("Editar");
        editar_exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_exercicioActionPerformed(evt);
            }
        });

        tabela_lista_exercicios.setModel(exercicioModel);
        jScrollPane1.setViewportView(tabela_lista_exercicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adicionar_novo_exercicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deletar_exercicio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(editar_exercicio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(adicionar_novo_exercicio)
                .addGap(18, 18, 18)
                .addComponent(deletar_exercicio)
                .addGap(18, 18, 18)
                .addComponent(editar_exercicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionar_novo_exercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionar_novo_exercicioActionPerformed
        JDialog dialog = new JDialog();
        ExercicioEdita formulario_edita = new ExercicioEdita(new Exercicio(), dialog, exercicioModel);
        dialog.add(formulario_edita);
        dialog.setSize(new Dimension(380, 320));

        dialog.setVisible(true);
    }//GEN-LAST:event_adicionar_novo_exercicioActionPerformed

    private void deletar_exercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_exercicioActionPerformed
        int linha_selecionada = tabela_lista_exercicios.getSelectedRow();
        Integer id_entidade = Integer.valueOf(tabela_lista_exercicios.getValueAt(linha_selecionada, 0).toString());
        Exercicio exercicio = exercicioControle.buscar(id_entidade);

        exercicioControle.excluir(exercicio);
        exercicioModel.deletar(linha_selecionada);
    }//GEN-LAST:event_deletar_exercicioActionPerformed

    private void editar_exercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_exercicioActionPerformed
        JDialog dialog = new JDialog();
        int linha_selecionada = tabela_lista_exercicios.getSelectedRow();
        Integer id_entidade = Integer.valueOf(tabela_lista_exercicios.getValueAt(linha_selecionada, 0).toString());
        Exercicio exercicio = exercicioControle.buscar(id_entidade);
        ExercicioEdita formulario_edita = new ExercicioEdita(exercicio, dialog, exercicioModel);
        dialog.add(formulario_edita);
        dialog.setSize(new Dimension(350, 280));

        dialog.setVisible(true);
    }//GEN-LAST:event_editar_exercicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionar_novo_exercicio;
    private javax.swing.JButton deletar_exercicio;
    private javax.swing.JButton editar_exercicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_lista_exercicios;
    // End of variables declaration//GEN-END:variables

    public void sincronizar() {
        exercicioControle.sincronizarExercicioModel();
    }

}
