/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.academia;

import com.mycompany.academia.lista.EquipamentoLista;
import com.mycompany.academia.lista.ExercicioLista;
import com.mycompany.academia.lista.MusculoAlvoLista;
import com.mycompany.academia.rotina.Rotina;
import javax.swing.JInternalFrame;

/**
 *
 * @author paulo
 */
public class Academia extends javax.swing.JFrame {

    private final EquipamentoLista equipamentoLista = new EquipamentoLista();
    private final ExercicioLista exercicioLista = new ExercicioLista();
    private final MusculoAlvoLista musculoalvoLista = new MusculoAlvoLista();

    /**
     * Creates new form Academia
     */
    public Academia() {
        initComponents();
        jDesktopPane1.add(equipamentoLista);
        jDesktopPane1.add(exercicioLista);
        jDesktopPane1.add(musculoalvoLista);
        jDesktopPane1.validate();

        equipamento_menu.addActionListener((e) -> {
            equipamentoLista.setVisible(!equipamentoLista.isVisible());
        });
        exercicio_menu.addActionListener((e) -> {
            exercicioLista.setVisible(!exercicioLista.isVisible());
        });
        musculo_alvo_menu.addActionListener((e) -> {
            musculoalvoLista.setVisible(!musculoalvoLista.isVisible());
        });
        rotina_novo.addActionListener((e) -> {
            JInternalFrame rotina = new Rotina();
            jDesktopPane1.add(rotina);
            rotina.setVisible(true);
            jDesktopPane1.validate();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        rotina_novo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        exercicio_menu = new javax.swing.JMenuItem();
        musculo_alvo_menu = new javax.swing.JMenuItem();
        equipamento_menu = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jDesktopPane1.setDragMode(jDesktopPane1.OUTLINE_DRAG_MODE);

        jMenu2.setText("Rotinas");

        rotina_novo.setText("Novo");
        jMenu2.add(rotina_novo);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Entidades");

        exercicio_menu.setText("Exercicio");
        jMenu1.add(exercicio_menu);

        musculo_alvo_menu.setText("Musculo Alvo");
        jMenu1.add(musculo_alvo_menu);

        equipamento_menu.setText("Equipamentos");
        jMenu1.add(equipamento_menu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Academia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem equipamento_menu;
    private javax.swing.JMenuItem exercicio_menu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem musculo_alvo_menu;
    private javax.swing.JMenuItem rotina_novo;
    // End of variables declaration//GEN-END:variables
}
