/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.academia;

import com.mycompany.academia.lista.ListaImagem;
import javax.swing.JInternalFrame;

/**
 *
 * @author paulo
 */
public class Academia extends javax.swing.JFrame {

    /**
     * Creates new form Academia
     */
    public Academia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        novaRotinaMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ExercicioMenu = new javax.swing.JMenuItem();
        ImagemMenu = new javax.swing.JMenuItem();
        ImagemKeywordMenu = new javax.swing.JMenuItem();
        KeywordsMenu = new javax.swing.JMenuItem();
        MovimentoMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1121, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        jDesktopPane1.setDragMode(jDesktopPane1.OUTLINE_DRAG_MODE);

        jMenu2.setText("Rotinas");

        novaRotinaMenu.setText("Novo");
        novaRotinaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaRotinaMenuActionPerformed(evt);
            }
        });
        jMenu2.add(novaRotinaMenu);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Entidades");

        ExercicioMenu.setText("Exercicio");
        jMenu1.add(ExercicioMenu);

        ImagemMenu.setText("Imagem");
        ImagemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImagemMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ImagemMenu);

        ImagemKeywordMenu.setText("ImagemKeyword");
        jMenu1.add(ImagemKeywordMenu);

        KeywordsMenu.setText("Keywords");
        jMenu1.add(KeywordsMenu);

        MovimentoMenu.setText("Movimento");
        jMenu1.add(MovimentoMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImagemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagemMenuActionPerformed
        JInternalFrame listaImagem = new ListaImagem();
        listaImagem.setVisible(true);

        jDesktopPane1.add(listaImagem);
        jDesktopPane1.validate();
    }//GEN-LAST:event_ImagemMenuActionPerformed

    private void novaRotinaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaRotinaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novaRotinaMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Academia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Academia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExercicioMenu;
    private javax.swing.JMenuItem ImagemKeywordMenu;
    private javax.swing.JMenuItem ImagemMenu;
    private javax.swing.JMenuItem KeywordsMenu;
    private javax.swing.JMenuItem MovimentoMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem novaRotinaMenu;
    // End of variables declaration//GEN-END:variables
}
