/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.academia.view.rotina;

import com.mycompany.academia.model.entidades.Exercicio;
import com.mycompany.academia.model.dto.ExercicioWrapper;
import com.mycompany.academia.services.Relatorio;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author paulo
 */
public class RotinaTablePanel extends javax.swing.JPanel {

    private int total_abas_adicionadas = 0;

    /**
     * Creates new form RotinaDireitaTable
     */
    public RotinaTablePanel() {
        initComponents();
        adicionar_aba();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelas = new javax.swing.JTabbedPane();
        nova_aba = new javax.swing.JButton();
        remover_aba = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        remover_exercicio = new javax.swing.JButton();
        resetar_formulario = new javax.swing.JButton();

        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(819, 551));

        nova_aba.setText("Adicionar aba");
        nova_aba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nova_abaMouseClicked(evt);
            }
        });

        remover_aba.setText("Remover aba");
        remover_aba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_abaActionPerformed(evt);
            }
        });

        imprimir.setText("Imprimir");
        imprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimirMouseClicked(evt);
            }
        });

        remover_exercicio.setText("Remover exercicio");
        remover_exercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_exercicioActionPerformed(evt);
            }
        });

        resetar_formulario.setBackground(new java.awt.Color(204, 0, 0));
        resetar_formulario.setForeground(new java.awt.Color(255, 255, 255));
        resetar_formulario.setText("Resetar");
        resetar_formulario.setToolTipText("Reseta o formulario");
        resetar_formulario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        resetar_formulario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resetar_formulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetar_formularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(janelas, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(remover_exercicio)
                    .addComponent(nova_aba)
                    .addComponent(remover_aba)
                    .addComponent(imprimir)
                    .addComponent(resetar_formulario))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelas)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(resetar_formulario)
                .addGap(18, 18, 18)
                .addComponent(nova_aba)
                .addGap(18, 18, 18)
                .addComponent(remover_exercicio)
                .addGap(18, 18, 18)
                .addComponent(remover_aba)
                .addGap(18, 18, 18)
                .addComponent(imprimir)
                .addContainerGap(325, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nova_abaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nova_abaMouseClicked
        adicionar_aba();
    }//GEN-LAST:event_nova_abaMouseClicked

    private void remover_abaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_abaActionPerformed
        if (janelas.getTabCount() == 1) {
            return;
        }
        int selected_tab = janelas.getSelectedIndex();
        janelas.remove(selected_tab);
    }//GEN-LAST:event_remover_abaActionPerformed

    private void remover_exercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_exercicioActionPerformed
        JTable table = (JTable) ((JScrollPane) janelas.getSelectedComponent()).getViewport().getView();
        RotinaTableModel table_model = (RotinaTableModel) table.getModel();
        int selected_row = table.getSelectedRow();
        if (selected_row < 0) {
            return;
        }
        table_model.removeExercicioWrapper(selected_row);
        atualizar_comboBox(table);
    }//GEN-LAST:event_remover_exercicioActionPerformed

    private void imprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimirMouseClicked
        ArrayList<String> titulos = get_titulos();
        ArrayList<ArrayList<ExercicioWrapper>> exercicios = get_exercicios();
        ArrayList<HashMap<ExercicioWrapper, ExercicioWrapper>> superset = get_superset();
        Relatorio.imprimirRelatorio(titulos, exercicios, superset);
    }//GEN-LAST:event_imprimirMouseClicked

    private void resetar_formularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetar_formularioActionPerformed
        janelas.removeAll();
        total_abas_adicionadas = 0;
        adicionar_aba();
    }//GEN-LAST:event_resetar_formularioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imprimir;
    private javax.swing.JTabbedPane janelas;
    private javax.swing.JButton nova_aba;
    private javax.swing.JButton remover_aba;
    private javax.swing.JButton remover_exercicio;
    private javax.swing.JButton resetar_formulario;
    // End of variables declaration//GEN-END:variables

    private void adicionar_aba() {
        // cria um novo Jtable
        JTable table = new JTable(new RotinaTableModel());
        // adiciona uma comboBox na tabela
        atualizar_comboBox(table);
        // cria a nova aba com um JTable
        String letra = Character.toString(65 + total_abas_adicionadas++);
        janelas.insertTab(letra, null, new JScrollPane(table), "", janelas.getTabCount());
    }

    public void adicionar_exercicio(Exercicio exercicio) {
        ExercicioWrapper novo_exercicio = new ExercicioWrapper(exercicio, 12, 3, 30);
        // Recupera o model para a JTable da aba ativa
        JTable table = (JTable) ((JScrollPane) janelas.getSelectedComponent()).getViewport().getView();
        RotinaTableModel table_model = (RotinaTableModel) table.getModel();
        // adiciona o novo exercicio no model da tabela atual
        table_model.addExercicioWrapper(novo_exercicio);
        // atualiza a comboBox para incluir o exercicio adicionado
        atualizar_comboBox(table);
    }

    private void atualizar_comboBox(JTable table) {
        JComboBox<Exercicio> comboBox = new JComboBox<>();

        int linhas = table.getModel().getRowCount();
        for (int i = 0; i < linhas; i++) {
            Exercicio exercicio = (Exercicio) table.getModel().getValueAt(i, 0);
            comboBox.addItem(exercicio);
        }
        comboBox.addItem(null);

        TableColumn superset_column = table.getColumnModel().getColumn(4);
        superset_column.setCellEditor(new DefaultCellEditor(comboBox));

    }

    private ArrayList<String> get_titulos() {
        ArrayList<String> titles = new ArrayList<>();
        for (int i = 0; i < janelas.getTabCount(); i++) {
            String title = janelas.getTitleAt(i);
            titles.add(title);
        }
        return titles;
    }

    private ArrayList<ArrayList<ExercicioWrapper>> get_exercicios() {
        ArrayList<ArrayList<ExercicioWrapper>> exercicios = new ArrayList<>();
        for (int i = 0; i < janelas.getTabCount(); i++) {
            JTable table = (JTable) ((JScrollPane) janelas.getComponentAt(i)).getViewport().getView();
            RotinaTableModel table_model = (RotinaTableModel) table.getModel();
            ArrayList<ExercicioWrapper> _exercicios = table_model.getExercicios();
            exercicios.add(_exercicios);
        }
        return exercicios;
    }

    private ArrayList<HashMap<ExercicioWrapper, ExercicioWrapper>> get_superset() {
        ArrayList<HashMap<ExercicioWrapper, ExercicioWrapper>> superset = new ArrayList<>();
        for (int i = 0; i < janelas.getTabCount(); i++) {
            JTable table = (JTable) ((JScrollPane) janelas.getComponentAt(i)).getViewport().getView();
            RotinaTableModel table_model = (RotinaTableModel) table.getModel();
            HashMap<ExercicioWrapper, ExercicioWrapper> superset_as_exercicio_wrapper = table_model.getSuperset();
            superset.add(superset_as_exercicio_wrapper);
        }
        return superset;
    }

}
